name: CI

on: [push]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: ğŸ“¥ Checkout the code
      - uses: actions/checkout@v3

      - name: ğŸ› ï¸ Set up Oracle JDK 19
        uses: oracle-actions/setup-java@v1
        with:
          release: 19

      - name: âœ”ï¸ Validate the Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: ğŸ—ï¸ Build the project with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: createDistributable

      - name: ğŸ“¤ Upload build artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/compose/binaries/main/app